ln /Applications/SPDPointsViewer.app/Contents/MacOS/spd2spd /usr/local/bin/spd2spd
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdclearclass /usr/local/bin/spdclearclass
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdconwave /usr/local/bin/spdconwave
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spddecomp /usr/local/bin/spddecomp
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spddefheight /usr/local/bin/spddefheight
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spddefrgb /usr/local/bin/spddefrgb
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdelevation /usr/local/bin/spdelevation
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdinfo /usr/local/bin/spdinfo
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdinterp /usr/local/bin/spdinterp
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdmccgrd /usr/local/bin/spdmccgrd
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdmerge /usr/local/bin/spdmerge
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdmetrics /usr/local/bin/spdmetrics
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdplanegrd /usr/local/bin/spdplanegrd
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdpmfgrd /usr/local/bin/spdpmfgrd
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdproj /usr/local/bin/spdproj
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdstats /usr/local/bin/spdstats
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdsubset /usr/local/bin/spdsubset
ln /Applications/SPDPointsViewer.app/Contents/MacOS/spdvecstats /usr/local/bin/spdvecstats
ln /Applications/SPDPointsViewer.app/Contents/MacOS/updsubset /usr/local/bin/updsubset
